requirementDiagram

    element moncompte_dawan_fr {
        type: system
        docref: moncompte.dawan.fr
    }

    requirement sAuthentifier {
        id: 1.0
        text: formulaire login/mdp
    }

    moncompte_dawan_fr - contains -> sAuthentifier
